### ISSUE TITLE
Failed to connect to OpenAI realtime

### ISSUE THREAD

**Issue by micuentadecasa** [Pierre-LouisBJT/yc-interview-prep#3]
I put here the error and the solution for the people that gets this error

when I try to activate the micro I got this error:

Failed to connect to OpenAI realtime: BaseEventLoop.create_connection() got an unexpected keyword argument 'additional_headers'

I had installed previous web sockets library, upgrading it to the latest makes it work.

pip install --upgrade websockets

in the requirements.txt there should be the version number required to run this.

**Comment by plbiojout** [comment]
Exactly, you need to have the latest version of websockets installed. Previous versions used `extra_headers` instead of `additional_headers`. I updated the `requirements.txt` file to prevent the issue.
